/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as TunablesRouteRouteImport } from './routes/tunables/route'
import { Route as NewsRouteRouteImport } from './routes/news/route'
import { Route as MaintenanceRouteRouteImport } from './routes/maintenance/route'
import { Route as CrewRouteRouteImport } from './routes/crew/route'
import { Route as IndexRouteImport } from './routes/index'

const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const TunablesRouteRoute = TunablesRouteRouteImport.update({
  id: '/tunables',
  path: '/tunables',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRouteRoute = NewsRouteRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRouteRoute = MaintenanceRouteRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRouteRoute = CrewRouteRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crew': typeof CrewRouteRoute
  '/maintenance': typeof MaintenanceRouteRoute
  '/news': typeof NewsRouteRoute
  '/tunables': typeof TunablesRouteRoute
  '/user': typeof UserRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crew': typeof CrewRouteRoute
  '/maintenance': typeof MaintenanceRouteRoute
  '/news': typeof NewsRouteRoute
  '/tunables': typeof TunablesRouteRoute
  '/user': typeof UserRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crew': typeof CrewRouteRoute
  '/maintenance': typeof MaintenanceRouteRoute
  '/news': typeof NewsRouteRoute
  '/tunables': typeof TunablesRouteRoute
  '/user': typeof UserRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crew' | '/maintenance' | '/news' | '/tunables' | '/user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crew' | '/maintenance' | '/news' | '/tunables' | '/user'
  id:
    | '__root__'
    | '/'
    | '/crew'
    | '/maintenance'
    | '/news'
    | '/tunables'
    | '/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrewRouteRoute: typeof CrewRouteRoute
  MaintenanceRouteRoute: typeof MaintenanceRouteRoute
  NewsRouteRoute: typeof NewsRouteRoute
  TunablesRouteRoute: typeof TunablesRouteRoute
  UserRouteRoute: typeof UserRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tunables': {
      id: '/tunables'
      path: '/tunables'
      fullPath: '/tunables'
      preLoaderRoute: typeof TunablesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrewRouteRoute: CrewRouteRoute,
  MaintenanceRouteRoute: MaintenanceRouteRoute,
  NewsRouteRoute: NewsRouteRoute,
  TunablesRouteRoute: TunablesRouteRoute,
  UserRouteRoute: UserRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
